services:
  node:
    build:
      context: ./
    image: wmde/query-builder
    volumes:
      - "~/.npm:/.npm"
      - "./:/app"
    working_dir: /app
    environment:
      # Ensures cypress installs and looks for it's binary in a project local directory
      - CYPRESS_CACHE_FOLDER=./.cache/cypress

  dev:
    extends:
      service: node
    command: npm run serve
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=development
